git-debimport quilt_0.60-2.debian.tar.gz

diff --git a/quilt/diff.in b/quilt/diff.in
--- a/quilt/diff.in
+++ b/quilt/diff.in
@@ -110,15 +110,15 @@ do_diff()
 	then
 		[ -s "$old_file" ] || old_file=/dev/null
 		[ -s "$new_file" ] || new_file=/dev/null
-		if ! diff -q $old_file $new_file >/dev/null
+		if ! diff -q "$old_file" "$new_file" >/dev/null
 		then
 			export LANG=$ORIGINAL_LANG
-			$opt_diff $old_file $new_file
+			$opt_diff "$old_file" "$new_file"
 			export LANG=POSIX
 			true
 		fi
 	else
-		diff_file $file $old_file $new_file | colorize
+		diff_file "$file" "$old_file" "$new_file" | colorize
 	fi
 }
 
@@ -229,11 +229,18 @@ case "$opt_strip_level" in
 0 | 1 | ab)
 	;;
 *)
-	printf $"Cannot diff patches with -p%s, please specify -p0 or -p1 instead\n" \
+	printf $"Cannot diff patches with -p%s, please specify -p0, -p1, or -pab instead\n" \
 	       "$opt_strip_level" >&2
 	die 1
 	;;
 esac
+
+# If diffing against snapshot, ensure that snapshot is actually present
+if [ -n "$opt_snapshot" ] && [ ! -d "$QUILT_PC/$snap_subdir" ]
+then
+	printf $"No snapshot to diff against\n" >&2
+	die 1
+fi
 
 trap "die 1" SIGTERM
 
@@ -274,6 +281,10 @@ else
 	patches=( $last_patch )
 fi
 
+# Properly handle spaces in file names
+saved_IFS=$IFS
+IFS=$'\n'
+
 for patch in ${patches[@]}
 do
 	for file in $(files_in_patch_ordered $patch)
@@ -303,12 +314,16 @@ else
 	files=( $(sort -u $tmp_files) )
 fi
 
+IFS=$saved_IFS
+
 if [ -n "$opt_relative" ]
 then
 	workdir=$(gen_tempfile -d $PWD/quilt)
 	apply_patch_temporarily "$workdir" "$last_patch" "${files[@]}" \
 	|| die 1
 fi
+
+setup_pager
 
 for file in "${files[@]}"
 do
@@ -319,22 +334,22 @@ do
 	then
 		old_file="$workdir/$file"
 	else
-		patch="$(first_modified_by $file ${patches[@]})"
+		patch=$(first_modified_by "$file" "${patches[@]}")
 		if [ -z "$patch" ]
 		then
 			[ -z "$opt_snapshot" ] \
 			&& printf $"File %s is not being modified\n" "$file" >&2
 			continue
 		fi
-		old_file="$(backup_file_name $patch $file)"
+		old_file=$(backup_file_name "$patch" "$file")
 	fi
 
-	next_patch=$(next_patch_for_file $last_patch $file)
+	next_patch=$(next_patch_for_file "$last_patch" "$file")
 	if [ -z "$next_patch" ]
 	then
 		new_file="$file"
 	else
-		new_file="$(backup_file_name $next_patch $file)"
+		new_file=$(backup_file_name "$next_patch" "$file")
 		files_were_shadowed=1
 	fi
 
