git-debimport quilt_0.63.orig.tar.gz

diff --git a/quilt/diff.in b/quilt/diff.in
--- a/quilt/diff.in
+++ b/quilt/diff.in
@@ -21,7 +21,7 @@ setup_colors
 
 usage()
 {
-	printf $"Usage: quilt diff [-p n|-p ab] [-u|-U num|-c|-C num] [--combine patch|-z] [-R] [-P patch] [--snapshot] [--diff=utility] [--no-timestamps] [--no-index] [--sort] [--color] [file ...]\n"
+	printf $"Usage: quilt diff [-p n|-p ab] [-u|-U num|-c|-C num] [--combine patch|-z] [-R] [-P patch] [--snapshot] [--diff=utility] [--no-timestamps] [--no-index] [--sort] [--color[=always|auto|never]] [file ...]\n"
 
 	if [ x$1 = x-h ]
 	then
@@ -69,7 +69,7 @@ included.
 	is invoked with the original and new file name as arguments.
 
 --color[=always|auto|never]
-	Use syntax coloring.
+	Use syntax coloring (auto activates it only if the output is a tty).
 
 --sort	Sort files by their name instead of preserving the original order.
 "
@@ -79,7 +79,8 @@ included.
 	fi
 }
 
-colorize() {
+colorize()
+{
 	if [ -n "$opt_color" ]
 	then
 		sed -e '
@@ -97,7 +98,7 @@ colorize() {
 
 do_diff()
 {
-	local file=$1 old_file=$2 new_file=$3
+	local file=$1 old_file=$2 new_file=$3 status
 
 	if [ -n "$opt_reverse" ]
 	then
@@ -119,6 +120,13 @@ do_diff()
 		fi
 	else
 		diff_file "$file" "$old_file" "$new_file" | colorize
+
+		# Test the return value of diff, and propagate the error if any
+		status=${PIPESTATUS[0]}
+		if [ $status != 0 ]
+		then
+			die $status
+		fi
 	fi
 }
 
@@ -149,7 +157,7 @@ do
 		opt_strip_level=$2
 		shift 2 ;;
 	-P)
-		last_patch="$2"
+		last_patch=$2
 		shift 2 ;;
 	--combine)
 		opt_combine=1
@@ -179,7 +187,7 @@ do
 		snap_subdir=.snap
 		shift ;;
 	--diff)
-		opt_diff="$2"
+		opt_diff=$2
 		shift 2 ;;
 	--no-timestamps)
 		QUILT_NO_DIFF_TIMESTAMPS=1
@@ -211,7 +219,7 @@ done
 
 QUILT_DIFF_OPTS="$QUILT_DIFF_OPTS $opt_format"
 
-opt_files=( $(for file in "$@"; do echo "$SUBDIR$file" ; done) )
+opt_files=( $(for file in "$@"; do echo "$SUBDIR${file#./}" ; done) )
 
 if [ $[0$opt_combine + 0$opt_snapshot + 0$opt_relative] -gt 1 ]
 then
@@ -223,7 +231,7 @@ last_patch=$(find_applied_patch "$last_patch") || exit 1
 
 if [ -z "$opt_strip_level" ]
 then
-	opt_strip_level=$(patch_strip_level $last_patch)
+	opt_strip_level=$(patch_strip_level "$last_patch")
 fi
 case "$opt_strip_level" in
 0 | 1 | ab)
@@ -251,17 +259,19 @@ if [ -n "$opt_snapshot" -a ${#opt_files[@]} -eq 0 ]
 then
 	# Add all files in the snapshot into the file list (they may all
 	# have changed).
-	files=( $(find $QUILT_PC/$snap_subdir -type f | sort) )
-	printf "%s\n" "${files[@]#$QUILT_PC/$snap_subdir/}" >&4
+	files=( $(find $QUILT_PC/$snap_subdir -type f \
+		  | sed -e "s/^$(quote_bre $QUILT_PC/$snap_subdir/)//" \
+		  | sort) )
+	printf "%s\n" "${files[@]}" >&4
 	unset files
 	# Also look at all patches that are currently applied.
 	opt_combine=1
-	first_patch="$(applied_patches | head -n 1)"
+	first_patch=$(applied_patches | head -n 1)
 fi
 
 if [ -n "$opt_combine" ]
 then
-	set -- $(patches_before $last_patch) $last_patch
+	set -- $(patches_before "$last_patch") "$last_patch"
 	if [ "$first_patch" != "-" ]
 	then
 		while [ $# -ge 1 -a "$1" != "$first_patch" ]
@@ -271,14 +281,14 @@ then
 		if [ $# -eq 0 ]
 		then
 			printf $"Patch %s not applied before patch %s\n" \
-			       "$(print_patch $first_patch)" \
-			       "$(print_patch $last_patch)" >&2
+			       "$(print_patch "$first_patch")" \
+			       "$(print_patch "$last_patch")" >&2
 			die 1
 		fi
 	fi
-	patches=( $@ )
+	patches=( "$@" )
 else
-	patches=( $last_patch )
+	patches=( "$last_patch" )
 fi
 
 # Properly handle spaces in file names
@@ -287,10 +297,10 @@ IFS=$'\n'
 
 for patch in ${patches[@]}
 do
-	for file in $(files_in_patch_ordered $patch)
+	for file in $(files_in_patch_ordered "$patch")
 	do
 		if [ ${#opt_files[@]} -gt 0 ] && \
-		   ! in_array "$file" "${opt_files[@]#./}"
+		   ! in_array "$file" "${opt_files[@]}"
 		then
 			continue
 		fi
@@ -347,7 +357,7 @@ do
 	next_patch=$(next_patch_for_file "$last_patch" "$file")
 	if [ -z "$next_patch" ]
 	then
-		new_file="$file"
+		new_file=$file
 	else
 		new_file=$(backup_file_name "$next_patch" "$file")
 		files_were_shadowed=1
@@ -365,7 +375,7 @@ done
 if [ -n "$files_were_shadowed" ]
 then
 	printf $"Warning: more recent patches modify files in patch %s\n" \
-	       "$(print_patch $last_patch)" >&2
+	       "$(print_patch "$last_patch")" >&2
 fi
 die 0
 ### Local Variables:
diff --git a/quilt/refresh.in b/quilt/refresh.in
--- a/quilt/refresh.in
+++ b/quilt/refresh.in
@@ -182,14 +182,14 @@ if [ -n "$opt_fork" ]; then
 		patch=$(next_filename "$patch")
 	fi
 	if [ -e "$(patch_file_name "$patch")" ]; then
-		printf $"Patch %s exists already\n" "$(print_patch $patch)" >&2
+		printf $"Patch %s exists already\n" "$(print_patch "$patch")" >&2
 		exit 1
 	fi
 fi
 
 if [ -z "$opt_strip_level" ]
 then
-	opt_strip_level=$(patch_strip_level $patch)
+	opt_strip_level=$(patch_strip_level "$patch")
 fi
 case "$opt_strip_level" in
 0 | 1)
@@ -199,7 +199,8 @@ ab)
 	num_strip_level=1
 	;;
 *)
-	printf $"Cannot refresh patches with -p%s, please specify -p0 or -p1 instead\n" "$opt_strip_level" >&2
+	printf $"Cannot refresh patches with -p%s, please specify -p0, -p1, or -pab instead\n" \
+	       "$opt_strip_level" >&2
 	exit 1
 	;;
 esac
@@ -231,13 +232,13 @@ do
 	fi
 	if ! diff_file "$file" "$old_file" "$new_file"
 	then
-		printf $"Diff failed, aborting\n" >&2
+		printf $"Diff failed on file '%s', aborting\n" "$new_file" >&2
 		die 1
 	fi
 
 	if [ -n "$files_were_shadowed" -a -z "$opt_force" ]
 	then
-		printf $"More recent patches modify files in patch %s. Enforce refresh with -f.\n" "$(print_patch $patch)" >&2
+		printf $"More recent patches modify files in patch %s. Enforce refresh with -f.\n" "$(print_patch "$patch")" >&2
 		die 1
 	fi
 
@@ -247,9 +248,9 @@ do
 	fi
 done >> $tmp_patch
 
-if ! [ -s $tmp_patch ]
+if [ -n "$opt_fork" -a ! -s $tmp_patch ]
 then
-	printf $"Nothing in patch %s\n" "$(print_patch $patch)" >&2
+	printf $"Nothing in patch %s\n" "$(print_patch "$patch")" >&2
 	die 1
 fi
 
@@ -269,7 +270,7 @@ else
 fi
 # FIXME: no stripping of non-topmost patch !!!
 
-patch_file=$(patch_file_name $patch)
+patch_file=$(patch_file_name "$patch")
 
 trap "" SIGINT
 
@@ -284,7 +285,7 @@ then
 	| awk '
 	    function print_diffstat(arr, i) {
 	      if (system("diffstat '"$QUILT_DIFFSTAT_OPTS \
-		      		     -p$num_strip_level \
+				     -p$num_strip_level \
 				     $tmp_patch | sed -e s:^:"'" prefix ":"))
 		exit 1
 	    }
@@ -302,7 +303,7 @@ then
 			{ print eat $0
 			  eat = "" }
 	    END		{ printf "%s", eat
-	    		  if (!diffstat_printed) {
+			  if (!diffstat_printed) {
 			    print "---"
 			    print_diffstat()
 			    print prefix
@@ -316,22 +317,22 @@ fi
 
 cat $tmp_patch >> $tmp_result
 
-mkdir -p $(dirname $patch_file)
+mkdir -p $(dirname "$patch_file")
 
-if [ -e $patch_file ] && \
-   diff -q $patch_file $tmp_result > /dev/null
+if [ -e "$patch_file" ] && \
+   diff -q "$patch_file" $tmp_result > /dev/null
 then
-	printf $"Patch %s is unchanged\n" "$(print_patch $patch)"
-elif ( [ -z "$QUILT_BACKUP" -o ! -e $patch_file ] || \
-       mv $patch_file $patch_file~ ) && \
-     cat_to_new_file $patch_file < $tmp_result
+	printf $"Patch %s is unchanged\n" "$(print_patch "$patch")"
+elif ( [ -z "$QUILT_BACKUP" -o ! -e "$patch_file" ] || \
+       mv "$patch_file" "$patch_file~" ) && \
+     cat_to_new_file "$patch_file" < $tmp_result
 then
 	if [ -n "$opt_fork" ]
 	then
 		if ! insert_in_series "$patch" "$old_patch_args"
 		then
 			printf $"Failed to insert patch %s into file series\n" \
-			       "$(print_patch $patch)" >&2
+			       "$(print_patch "$patch")" >&2
 			rm -f "$patch_file"
 			exit 1
 		fi
@@ -340,22 +341,27 @@ then
 		   ! echo "$patch" >> $QUILT_PC/applied-patches
 		then
 			printf $"Failed to create patch %s\n" \
-			       "$(print_patch $patch)" >&2
+			       "$(print_patch "$patch")" >&2
 			exit 1
 		fi
 		printf $"Fork of patch %s created as %s\n" \
-			"$(print_patch $old_patch)" \
-			"$(print_patch $patch)"
+			"$(print_patch "$old_patch")" \
+			"$(print_patch "$patch")"
 	else
-		printf $"Refreshed patch %s\n" "$(print_patch $patch)"
+		if [ -s $tmp_patch ]
+		then
+			printf $"Refreshed patch %s\n" "$(print_patch "$patch")"
+		else
+			printf $"Nothing in patch %s\n" "$(print_patch "$patch")"
+		fi
 	fi
-	touch $QUILT_PC/$patch/.timestamp
+	touch "$QUILT_PC/$patch/.timestamp"
 else
 	die 1
 fi
 
-rm -f $QUILT_PC/$patch~refresh
-if ! change_db_strip_level -p$num_strip_level $patch
+rm -f "$QUILT_PC/$patch~refresh"
+if ! change_db_strip_level -p$num_strip_level "$patch"
 then
 	die 1
 fi
diff --git a/quilt/scripts/patchfns.in b/quilt/scripts/patchfns.in
--- a/quilt/scripts/patchfns.in
+++ b/quilt/scripts/patchfns.in
@@ -47,7 +47,8 @@ fi
 
 declare -a exit_handlers
 
-add_exit_handler() {
+add_exit_handler()
+{
 	exit_handlers[${#exit_handlers[@]}]=$1
 }
 
@@ -76,6 +77,20 @@ trap run_exit_handlers EXIT
 
 # ========================================================
 
+# Join multiple stings using the given separator.
+array_join()
+{
+	local sep=$1 str=$2
+	shift 2
+
+	printf %s "$str"
+
+	for str in "$@"
+	do
+		printf %s%s "$sep" "$str"
+	done
+}
+
 # Quote a string for use in a basic regular expression.
 quote_bre()
 {
@@ -86,6 +101,12 @@ quote_bre()
 quote_re()
 {
 	echo "$1" | sed -e 's:\([][?{(|)}^$/.+*\\]\):\\\1:g'
+}
+
+# Quote a string for use in a globing pattern.
+quote_glob()
+{
+	echo "$1" | sed -e 's:\([][*?\\]\):\\\1:g'
 }
 
 patch_file_name()
@@ -175,7 +196,7 @@ change_db_strip_level()
 				}
 			  }
 			  if (!p_printed && "'"$level"'" != "")
-			  	insert_arg(2, "'"$level"'")
+				insert_arg(2, "'"$level"'")
 			}
 			{ print }
 		' $SERIES > $tmpfile
@@ -193,11 +214,11 @@ patch_in_series()
 {
 	local patch=$1
 
-	if ! [ -e $SERIES ]
+	if [ -e $SERIES ]
 	then
-		return 1
-	else
 		grep -q "^$(quote_bre $patch)\([ \t]\|$\)" $SERIES
+	else
+		return 1
 	fi
 }
 
@@ -257,7 +278,7 @@ remove_from_series()
 	if [ $? -ne 0 ]
 	then
 		rm -f $tmpfile
-	   	return 1
+		return 1
 	fi
 	cat $tmpfile > $SERIES
 	rm -f $tmpfile
@@ -363,7 +384,7 @@ applied_before()
 		' $DB
 	fi
 }
-		
+
 patches_before()
 {
 	local patch=$1
@@ -422,7 +443,7 @@ next_patch_for_file()
 	then
 		for patch in $patches_on_top
 		do
-			if [ -f $(backup_file_name $patch $file) ]
+			if file_in_patch "$file" $patch
 			then
 				echo $patch
 				break
@@ -557,12 +578,12 @@ find_applied_patch()
 		local patch
 
 		patch=$(find_patch "$name") || return 1
-	        if ! is_applied "$patch"
-	        then
-	                printf $"Patch %s is not applied\n" \
+		if ! is_applied "$patch"
+		then
+			printf $"Patch %s is not applied\n" \
 			       "$(print_patch $patch)" >&2
-	                return 1
-	        fi
+			return 1
+		fi
 		echo "$patch"
 	else
 		find_top_patch
@@ -578,12 +599,12 @@ find_unapplied_patch()
 		local patch
 
 		patch=$(find_patch "$name") || return 1
-	        if is_applied "$patch"
-	        then
+		if is_applied "$patch"
+		then
 			printf $"Patch %s is currently applied\n" \
 				"$(print_patch $patch)" >&2
-               		return 1
-	        fi
+			return 2
+		fi
 		echo "$patch"
 	else
 		local start
@@ -592,48 +613,15 @@ find_unapplied_patch()
 		then
 			patch_after "$start"
 		else
-			find_first_patch || return 1
+			find_first_patch || return 2
 		fi
 		if [ $? -ne 0 ]
 		then
 			printf $"File series fully applied, ends at patch %s\n" \
 				"$(print_patch $start)" >&2
-			return 1
+			return 2
 		fi
 	fi
-}
-
-find_patch_file()
-{
-	local name="$1"
-
-	if [ ${name:0:1} = / ]
-	then
-		# Patch has absolute path
-		if [ -r "$name" ]
-		then
-			echo "$name"
-			return
-		fi
-	else
-		# Patch has a relative path
-		if [ -r "$SUBDIR$name" ]
-		then
-			echo "$SUBDIR$name"
-			return
-		fi
-	fi
-
-	local patch
-
-	patch=$(find_patch_in_series "$name" 2>/dev/null)
-	if [ -z "$patch" ]
-	then
-		printf $"Patch %s does not exist\n" "$name" >&2
-		return 1
-	fi
-
-	echo $(patch_file_name "$patch")
 }
 
 file_in_patch()
@@ -650,8 +638,8 @@ files_in_patch()
 	if [ -d "$path" ]
 	then
 		find "$path" -type f \
-			       -a ! -path "$path/.timestamp" |
-		sed -e "s:$path/::"
+			       -a ! -path "$(quote_glob "$path")/.timestamp" |
+		sed -e "s/$(quote_bre "$path")\///"
 	fi
 }
 
@@ -718,30 +706,30 @@ diff_file()
 		new_hdr=$dir/$file
 	fi
 	index=$new_hdr
-	
-	if ! [ -s "$old_file" ]
+
+	if [ -s "$old_file" ]
 	then
+		[ -n "$QUILT_NO_DIFF_TIMESTAMPS" ] \
+		|| old_date=$'\t'$(date +'%Y-%m-%d %H:%M:%S.%N %z' \
+					-r "$old_file")
+	else
 		old_file=/dev/null
 		old_hdr=/dev/null
 		[ -n "$QUILT_NO_DIFF_TIMESTAMPS" ] \
 		|| old_date=$'\t'"1970-01-01 00:00:00.000000000 +0000"
-	else
-		[ -n "$QUILT_NO_DIFF_TIMESTAMPS" ] \
-		|| old_date=$'\t'$(date +'%Y-%m-%d %H:%M:%S.%N %z' \
-					-r "$old_file")
 	fi
-	if ! [ -s "$new_file" ]
+	if [ -e "$new_file" ]
 	then
+		[ -n "$QUILT_NO_DIFF_TIMESTAMPS" ] \
+		|| new_date=$'\t'$(date +'%Y-%m-%d %H:%M:%S.%N %z' \
+					-r "$new_file")
+	else
 		[ $opt_strip_level = 0 ] \
 		&& old_hdr=$new_hdr
 		new_file=/dev/null
 		new_hdr=/dev/null
 		[ -n "$QUILT_NO_DIFF_TIMESTAMPS" ] \
 		|| new_date=$'\t'"1970-01-01 00:00:00.000000000 +0000"
-	else
-		[ -n "$QUILT_NO_DIFF_TIMESTAMPS" ] \
-		|| new_date=$'\t'$(date +'%Y-%m-%d %H:%M:%S.%N %z' \
-					-r "$new_file")
 	fi
 
 	diff $QUILT_DIFF_OPTS \
@@ -757,12 +745,18 @@ diff_file()
 		echo "$line"
 		cat
 	fi
+
+	# Test the return value of diff, and propagate the error retcode if any
+	if [ ${PIPESTATUS[0]} == 2 ]
+	then
+		return 1
+	fi
 }
 
 cat_file()
 {
 	local filename
-	
+
 	for filename in "$@"
 	do
 		if [ -e "$filename" ]
@@ -881,7 +875,7 @@ apply_patch_temporarily()
 	local prefix=$QUILT_PC/$patch/
 	[ ${prefix:0:1} == / ] || prefix=$PWD/$prefix
 	if ! ( cd $workdir && \
-	       $QUILT_DIR/scripts/backup-files -B $prefix -r -k -s ${@:--} )
+	       $QUILT_DIR/scripts/backup-files -B $prefix -r -k -s "${@:--}" )
 	then
 		printf $"Failed to copy files to temporary directory\n" >&2
 		return 1
@@ -891,7 +885,7 @@ apply_patch_temporarily()
 	then
 		if ! cat_file $patch_file \
 		     | patch -d $workdir $QUILT_PATCH_OPTS $patch_args \
-		     	     --no-backup-if-mismatch -Ef \
+			     --no-backup-if-mismatch -f \
 			     >/dev/null 2>/dev/null
 		then
 			# Generating a relative diff for a subset of files in
@@ -911,14 +905,15 @@ apply_patch_temporarily()
 next_filename()
 {
 	local patch=$1 base num
-        base=$(echo "$patch" \
-               | sed -r -e 's:(\.gz|\.bz2|\.xz|\.lzma)$::' -e 's:(\.diff?|\.patch)$::')
-        num=$(echo "$base" | sed -nre 's:.*-([0-9]+)$:\1:'p)
-        [ -n "$num" ] || num=1
-        echo "${base%-$num}-$((num+1))${patch#$base}"
+	base=$(echo "$patch" \
+	       | sed -r -e 's:(\.gz|\.bz2|\.xz|\.lzma)$::' -e 's:(\.diff?|\.patch)$::')
+	num=$(echo "$base" | sed -nre 's:.*-([0-9]+)$:\1:'p)
+	[ -n "$num" ] || num=1
+	echo "${base%-$num}-$((num+1))${patch#$base}"
 }
 
-create_db() {
+create_db()
+{
 	if ! [ -e $QUILT_PC ]
 	then
 		mkdir -p $QUILT_PC
@@ -934,7 +929,8 @@ create_db() {
 	fi
 }
 
-version_check() {
+version_check()
+{
 	[ -e $QUILT_PC ] || return 0
 
 	if [ -e $QUILT_PC/.version ]
@@ -952,13 +948,22 @@ version_check() {
 	return 1
 }
 
-print_patch() {
-	echo -n "${QUILT_PATCHES_PREFIX:+$SUBDIR_DOWN$QUILT_PATCHES/}$1"
+print_patch()
+{
+	echo "${QUILT_PATCHES_PREFIX:+$SUBDIR_DOWN$QUILT_PATCHES/}$1"
+}
+
+# Generate a format suitable to print patch names with printf
+patch_format()
+{
+	local prefix=${QUILT_PATCHES_PREFIX:+$SUBDIR_DOWN$QUILT_PATCHES/}
+
+	echo -n "${prefix/\%/%%}%s"
 }
 
 setup_colors()
 {
-	local C=diff_hdr=32:diff_add=36:diff_mod=35:diff_rem=35:diff_hunk=33:diff_ctx=35:diff_cctx=33:patch_offs=33:patch_fuzz=35:patch_fail=31:patch_applied=32:series_app=32:series_top=33:series_una=00:clear=00
+	local C=diff_hdr=32:diff_add=36:diff_mod=35:diff_rem=35:diff_hunk=33:diff_ctx=35:diff_cctx=33:patch_offs=33:patch_fuzz=35:patch_fail=31:series_app=32:series_top=33:series_una=00:clear=00
 	[ -n "$QUILT_COLORS" ] && C="$C:$QUILT_COLORS"
 
 	C=${C//=/=\'$'\e'[}
@@ -996,9 +1001,9 @@ setup_pager()
 {
 	test -t 1 || return 0
 
-	# QUILT_PAGER = QUILT_PAGER | GIT_PAGER | PAGER | less
+	# QUILT_PAGER = QUILT_PAGER | GIT_PAGER | PAGER | less -R
 	# NOTE: QUILT_PAGER='' is significant
-	QUILT_PAGER=${QUILT_PAGER-${GIT_PAGER-${PAGER-less}}}
+	QUILT_PAGER=${QUILT_PAGER-${GIT_PAGER-${PAGER-less -R}}}
 
 	[ -z "$QUILT_PAGER" -o "$QUILT_PAGER" = "cat" ]  && return 0
 
